# Generated by Django 5.0.6 on 2024-08-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_pass1_firsts_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firsts',
        ),
    ]
